Repository Webperf-se/webperf_core, pull requests merged in 2024-05, with the labels that each got.

#445 Great number of Docker Improvements
  .github/workflows/create-release.yml
  .github/workflows/regression-test-404.yml
  .github/workflows/regression-test-a11y-statement.yml
  .github/workflows/regression-test-css.yml
  .github/workflows/regression-test-docker-image.yml
  .github/workflows/regression-test-email.yml
  .github/workflows/regression-test-google-lighthouse-based.yml
  .github/workflows/regression-test-html.yml
  .github/workflows/regression-test-http.yml
  .github/workflows/regression-test-pa11y.yml
  .github/workflows/regression-test-sitespeed.yml
  .github/workflows/regression-test-software.yml
  .github/workflows/regression-test-standard-files.yml
  .github/workflows/regression-test-tracking.yml
  .github/workflows/regression-test-translations.yml
  .github/workflows/regression-test-webbkoll.yml
  .github/workflows/regression-test-ylt.yml
  .github/workflows/verify_result.py
  Dockerfile
Labels: enhancement

#457 Fix bug where sitespeed ignored REVIEW_SHOW_IMPROVEMENTS_ONLY setting
  tests/performance_sitespeed_io.py
Labels: bug

#458 Added markdown output support
  default.py
  docs/getting-started.md
  engines/csv_engine.py
  engines/gov.py
  engines/json_engine.py
  engines/markdown_engine.py
  engines/sql.py
  engines/sqlite.py
  locales/en/LC_MESSAGES/http_validator.mo
  locales/en/LC_MESSAGES/http_validator.po
  locales/en/LC_MESSAGES/webperf-core.mo
  locales/en/LC_MESSAGES/webperf-core.po
  locales/gov/LC_MESSAGES/http_validator.mo
  locales/gov/LC_MESSAGES/http_validator.po
  locales/gov/LC_MESSAGES/webperf-core.mo
  locales/gov/LC_MESSAGES/webperf-core.po
  locales/sv/LC_MESSAGES/http_validator.mo
  locales/sv/LC_MESSAGES/http_validator.po
  locales/sv/LC_MESSAGES/webperf-core.mo
  locales/sv/LC_MESSAGES/webperf-core.po
  models.py
  tests/lighthouse_base.py
  utils.py
Labels: enhancement

#466 Cleanup root folder by creating defaults and tools folder
  .github/workflows/codeql-analysis.yml
  .github/workflows/pylint.yml
  .github/workflows/regression-test-404.yml
  .github/workflows/regression-test-a11y-statement.yml
  .github/workflows/regression-test-css.yml
  .github/workflows/regression-test-docker-image.yml
  .github/workflows/regression-test-email.yml
  .github/workflows/regression-test-google-lighthouse-based.yml
  .github/workflows/regression-test-html.yml
  .github/workflows/regression-test-http.yml
  .github/workflows/regression-test-pa11y.yml
  .github/workflows/regression-test-sitespeed.yml
  .github/workflows/regression-test-software.yml
  .github/workflows/regression-test-standard-files.yml
  .github/workflows/regression-test-tracking.yml
  .github/workflows/regression-test-translations.yml
  .github/workflows/regression-test-webbkoll.yml
  .github/workflows/regression-test-ylt.yml
  .github/workflows/update-docker.yml
  .github/workflows/update-software.yml
  .gitignore
  SAMPLE-sitespeed-rules.json
  defaults/__init__.py
  defaults/analytics-rules.json
  defaults/config.py
  defaults/software-rules.json
  docs/config-py.md
  docs/getting-started-docker.md
  docs/getting-started-local.md
  docs/getting-started-others.md
  docs/tests/sitespeed.md
  docs/tests/software.md
  docs/tests/tracking.md
  tests/software.py
  tests/tracking_validator.py
  tests/utils.py
  tools/carbon_rating.py
  tools/filter_unknown_sources.py
  tools/release.py
  tools/verify_result.py
  tools/verify_translations.py
  update_software.py
  utils.py
Labels: breaking-change

#467 Keep default useragent up to date
  .github/workflows/regression-test-sitespeed.yml
  .github/workflows/update-docker.yml
  .github/workflows/update-software.yml
  defaults/config.py
  tools/verify_result.py
  update_software.py
Labels: enhancement

#469 Use version specific w3c validator for HTML/CSS Tests
  .github/workflows/regression-test-css.yml
  .github/workflows/regression-test-html.yml
  Dockerfile
  docs/tests/css.md
  docs/tests/html.md
  package.json
  tests/w3c_base.py
Labels: breaking-change

#470 Update prep-release.yml
  .github/workflows/prep-release.yml
Labels: ignore-for-release

#472 Update create-release.yml
  .github/workflows/create-release.yml
Labels: ignore-for-release

#476 Clear `failures.log` file on every new run
  default.py
  utils.py
Labels: enhancement

#477 Fix path to msgfmt.py so translations can be generated correctly
  tools/verify_translations.py
Labels: bug

#480 Change so tests return -1 in rating if Tests are unable to connect
  helpers/sitespeed_helper.py
  locales/en/LC_MESSAGES/webperf-core.mo
  locales/en/LC_MESSAGES/webperf-core.po
  locales/gov/LC_MESSAGES/webperf-core.mo
  locales/gov/LC_MESSAGES/webperf-core.po
  locales/sv/LC_MESSAGES/webperf-core.mo
  locales/sv/LC_MESSAGES/webperf-core.po
  tests/a11y_pa11y.py
  tests/a11y_statement.py
  tests/css_validator_w3c.py
  tests/energy_efficiency.py
  tests/frontend_quality_yellow_lab_tools.py
  tests/html_validator_w3c.py
  tests/http_validator.py
  tests/lighthouse_base.py
  tests/page_not_found.py
  tests/performance_sitespeed_io.py
  tests/privacy_webbkollen.py
  tests/sitespeed_base.py
  tests/software.py
  tests/standard_files.py
  tests/tracking_validator.py
  tests/utils.py
  tests/w3c_base.py
  tools/verify_result.py
Labels: enhancement

#485 PyLint for Improved Code Quality - tests/software.py
  tests/software.py
Labels: ignore-for-release

#487 PyLint for Improved Code Quality - tests/software.py
  tests/http_validator.py
  tests/software.py
Labels: ignore-for-release

#489 Temporarily Apply Configuration for Current Run from Command Line
  default.py
  helpers/csp_helper.py
  helpers/setting_helper.py
  helpers/tls_helper.py
  locales/en/LC_MESSAGES/webperf-core.mo
  locales/en/LC_MESSAGES/webperf-core.po
  locales/gov/LC_MESSAGES/webperf-core.mo
  locales/gov/LC_MESSAGES/webperf-core.po
  locales/sv/LC_MESSAGES/webperf-core.mo
  locales/sv/LC_MESSAGES/webperf-core.po
  tests/a11y_pa11y.py
  tests/a11y_statement.py
  tests/css_validator_w3c.py
  tests/email_validator.py
  tests/frontend_quality_yellow_lab_tools.py
  tests/html_validator_w3c.py
  tests/http_validator.py
  tests/lighthouse_base.py
  tests/page_not_found.py
  tests/performance_sitespeed_io.py
  tests/privacy_webbkollen.py
  tests/sitespeed_base.py
  tests/software.py
  tests/standard_files.py
  tests/tracking_validator.py
  tests/utils.py
  tests/w3c_base.py
  update_software.py
  utils.py
Labels: enhancement

#491 Enhancing Lighthouse and Yellow Lab Tools by Focusing on Local Support
  .github/workflows/regression-test-google-lighthouse-based.yml
  .github/workflows/regression-test-ylt.yml
  defaults/config.py
  docs/config-py.md
  docs/tests/google-lighthouse-based.md
  docs/tests/yellowlab.md
  helpers/setting_helper.py
  tests/frontend_quality_yellow_lab_tools.py
  tests/lighthouse_base.py
  utils.py
Labels: breaking-change

#492 Convert `SAMPLE-config.py` and `config.py` to `settings.json` Configuration
  .github/workflows/pylint.yml
  .github/workflows/regression-test-404.yml
  .github/workflows/regression-test-a11y-statement.yml
  .github/workflows/regression-test-css.yml
  .github/workflows/regression-test-docker-image.yml
  .github/workflows/regression-test-email.yml
  .github/workflows/regression-test-google-lighthouse-based.yml
  .github/workflows/regression-test-html.yml
  .github/workflows/regression-test-http.yml
  .github/workflows/regression-test-pa11y.yml
  .github/workflows/regression-test-sitespeed.yml
  .github/workflows/regression-test-software.yml
  .github/workflows/regression-test-standard-files.yml
  .github/workflows/regression-test-tracking.yml
  .github/workflows/regression-test-webbkoll.yml
  .github/workflows/regression-test-ylt.yml
  .github/workflows/update-docker.yml
  .github/workflows/update-software.yml
  .gitignore
  Dockerfile
  README.md
  defaults/__init__.py
  defaults/config.py
  defaults/settings.json
  docs/config-py.md
  docs/getting-started-docker.md
  docs/getting-started-github-actions.md
  docs/getting-started-local.md
  docs/getting-started-others.md
  docs/getting-started.md
  docs/settings-json.md
  docs/tests/sitespeed.md
  docs/tests/software.md
  helpers/csp_helper.py
  helpers/setting_helper.py
  helpers/tls_helper.py
  tests/a11y_pa11y.py
  tests/a11y_statement.py
  tests/css_validator_w3c.py
  tests/email_validator.py
  tests/frontend_quality_yellow_lab_tools.py
  tests/html_validator_w3c.py
  tests/http_validator.py
  tests/lighthouse_base.py
  tests/page_not_found.py
  tests/performance_sitespeed_io.py
  tests/privacy_webbkollen.py
  tests/sitespeed_base.py
  tests/software.py
  tests/standard_files.py
  tests/tracking_validator.py
  tests/utils.py
  tests/w3c_base.py
  tools/verify_result.py
  update_software.py
  utils.py
Labels: breaking-change

#499 Lighthouse based test crashes when unable to connect to Chrome
  tests/lighthouse_base.py
Labels: bug

#500 Make it possible to exclude tests
  default.py
  docs/getting-started.md
Labels: enhancement

#507 Fixed broken software and useragent update
  .github/workflows/update-software.yml
  defaults/settings.json
  helpers/setting_helper.py
  software-full.json
  update_software.py
Labels: bug
