Repository Webperf-se/webperf_core, pull requests merged in 2024-09, with the labels that each got.

#626 Improve CSP Recommendation to allow for sha256 generation of binary content
  Dockerfile
  docs/settings-json.md
  helpers/csp_helper.py
  helpers/setting_helper.py
Labels: enhancement

#633 Added missing mo translation changes
  locales/en/LC_MESSAGES/http_validator.mo
  locales/gov/LC_MESSAGES/http_validator.mo
  locales/sv/LC_MESSAGES/http_validator.mo
Labels: bug

#635 Added Dependency Checks Using New Tool
  tools/dependency.py
Labels: enhancement

#641 Hosting change for Webbkoll
  .github/FUNDING.yml
  docs/CONTRIBUTING.md
  docs/tests/webbkoll.md
  tests/privacy_webbkollen.py
Labels: breaking-change

#642 Add basic Subresource Integrity (SRI) Validation
  helpers/sitespeed_helper.py
  helpers/sri_helper.py
  locales/en/LC_MESSAGES/http_validator.mo
  locales/en/LC_MESSAGES/http_validator.po
  locales/gov/LC_MESSAGES/http_validator.mo
  locales/gov/LC_MESSAGES/http_validator.po
  locales/sv/LC_MESSAGES/http_validator.mo
  locales/sv/LC_MESSAGES/http_validator.po
  tests/http_validator.py
Labels: enhancement
