Repository Webperf-se/webperf_core, pull requests merged in 2024-06, with the labels that each got.

#516 Added support for running lighthouse in our docker container without a interactive shell
  Dockerfile
  default.py
  defaults/settings.json
  docs/settings-json.md
  helpers/setting_helper.py
  locales/en/LC_MESSAGES/webperf-core.mo
  locales/en/LC_MESSAGES/webperf-core.po
  locales/gov/LC_MESSAGES/webperf-core.mo
  locales/gov/LC_MESSAGES/webperf-core.po
  locales/sv/LC_MESSAGES/webperf-core.mo
  locales/sv/LC_MESSAGES/webperf-core.po
  tests/lighthouse_base.py
Labels: enhancement

#528 Make calls to sitespeedio/sitespeed.io version specific
  tests/performance_sitespeed_io.py
  tests/sitespeed_base.py
  tests/utils.py
  utils.py
Labels: enhancement

#531 Add language from terminal options to settings.json
  default.py
  defaults/settings.json
  docs/settings-json.md
  helpers/setting_helper.py
  tests/a11y_lighthouse.py
  tests/a11y_pa11y.py
  tests/a11y_statement.py
  tests/best_practice_lighthouse.py
  tests/css_validator_w3c.py
  tests/email_validator.py
  tests/energy_efficiency.py
  tests/frontend_quality_yellow_lab_tools.py
  tests/html_validator_w3c.py
  tests/http_validator.py
  tests/page_not_found.py
  tests/performance_lighthouse.py
  tests/performance_sitespeed_io.py
  tests/privacy_webbkollen.py
  tests/seo_lighthouse.py
  tests/software.py
  tests/standard_files.py
  tests/tracking_validator.py
  utils.py
Labels: enhancement

#545 Use browser to check what TLS versions we support
  helpers/sitespeed_helper.py
  helpers/tls_helper.py
  tests/http_validator.py
Labels: enhancement

#554 Lets test lowering sitespeed default timeout to 30 seconds
  defaults/settings.json
Labels: enhancement

#556 GitHub Actions - Manually start test for provided url and test number
  .github/workflows/manual-start-test.yml
Labels: enhancement

#557 fix small bugs for new manual github action flow
  .github/workflows/manual-start-test.yml
Labels: ignore-for-release

#560 Fix condition for adding --xvfb to sitespeed args
  tests/http_validator.py
  tests/page_not_found.py
  tests/performance_sitespeed_io.py
  tests/software.py
  tests/tracking_validator.py
  tests/w3c_base.py
  update_software.py
Labels: bug

#558 Only require CSP when HTML content is not empty
  helpers/csp_helper.py
  tests/http_validator.py
Labels: bug
