Repository Webperf-se/webperf_core, pull requests merged in 2024-12, with the labels that each got.

#755 CSS Test - Don't report use of at rule layer as errors
  tests/css_validator_w3c.py
Labels: bug

#754 CSS Test - Don't report use of custom properties as errors
  tests/css_validator_w3c.py
Labels: bug

#759 Test 26 - A11y Statement gives too high rating
  tests/a11y_statement.py
Labels: bug

#764 CSS Test - All validated files not included in data object
  tests/css_validator_w3c.py
Labels: bug

#765 CSS (Lint) Test - All validated files not included in data object
  tests/css_linting.py
Labels: bug

#766 Cache key created for a resource sometimes differ depending context
  tests/utils.py
Labels: bug

#767 CSS (Lint) Test - Better handling of redirects
  tests/lint_base.py
Labels: bug

#757 Sitespeed.io - Validating browsertime.har fields and structure
  .github/workflows/regression-test-sitespeed-browsertime-har.yml
  .github/workflows/update-docker.yml
  .github/workflows/verify_browsertime_har.py
  .github/workflows/verify_result.py
Labels: enhancement

#774 Documentation for test CSS linting
  docs/tests/css-linting.md
Labels: documentation

#775 Update README.md with linkt to css linting page
  README.md
  docs/tests/README.md
Labels: documentation, ignore-for-release

#777 Update Softwares - Crashes when trying to get github repo versions
  helpers/update_software_helper.py
Labels: bug

#779 Update Softwares - unable to get CVE:s for openssl
  helpers/update_software_helper.py
Labels: bug

#783 Beginning of offline unittests
  .github/workflows/regression-test-lint-css.yml
  defaults/settings.json
  engines/sitespeed_result.py
  helpers/setting_helper.py
  tests/sitespeed_base.py
  unittests/webperf.se/test-27-no-errors.har
  unittests/webperf.se/test-27-with-errors.har
Labels: enhancement

#789 Removed requirement of workflow permission for validating sitespeed results
  .github/workflows/regression-test-sitespeed-browsertime-har.yml
  .github/workflows/update-docker.yml
  .github/workflows/verify_result.py
Labels: bug

#790 CSS Test - Regression test use offline version
  .github/workflows/regression-test-css.yml
  unittests/webperf.se/test-07-with-errors.har
Labels: enhancement

#791 Html Test - Regression test use offline version
  .github/workflows/regression-test-html.yml
  unittests/webperf.se/test-06-no-errors.har
Labels: enhancement

#794 404 Test - Regression test use offline version
  .github/workflows/regression-test-404.yml
  defaults/settings.json
  helpers/setting_helper.py
  tests/page_not_found.py
  unittests/webperf.se/test-02-no-errors.har
Labels: enhancement

#796 Tracking Test - Regression test use offline version
  .github/workflows/regression-test-tracking.yml
  unittests/webperf.se/test-23.har
Labels: enhancement

#795 Software Test - Regression test use offline version
  .github/workflows/regression-test-software.yml
  unittests/webperf.se/test-25-with-errors.har
Labels: enhancement

#797 Regression Tests - Sitespeed based, setting cache time was missing
  .github/workflows/regression-test-404.yml
  .github/workflows/regression-test-css.yml
  .github/workflows/regression-test-html.yml
  .github/workflows/regression-test-lint-css.yml
  .github/workflows/regression-test-software.yml
  .github/workflows/regression-test-tracking.yml
Labels: bug

#799 CSS Test - Updated documentation to reflect changes
  docs/tests/css.md
Labels: documentation

#800 HTTP (CSP Only) Test - Regression test use offline version
  unittests/webperf.se/test-21-CSP.har
Labels: enhancement

#801 Accessibility Statement - Use sitespeed to request webpages
  tests/a11y_statement.py
Labels: enhancement

#802 Accessibility Statement Test - Regression test use offline version
  .github/workflows/regression-test-a11y-statement.yml
  unittests/msb.se/test-26-accessibility-statement.har
  unittests/msb.se/test-26-startpage.har
Labels: enhancement

#810 Remove colon from *all SPF directives. Fixes #809
  tests/email_validator.py
Labels: bug

#822 Software Definition Update - Fix openssl CVE discovery
  CREDITS.md
  defaults/mdn-rules.json
  defaults/software-full.json
  helpers/update_software_helper.py
Labels: bug

#825 Software Test - Make javascript versions detection distinct
  chrome-versions.cjs
Labels: bug

#827 Fix bug where --find-unknown-source crashed
  helpers/update_software_helper.py
  tests/software.py
Labels: bug

#829 Removed duplicate postscript calls
  tests/a11y_statement.py
  tests/lint_base.py
  tests/page_not_found.py
  tests/software.py
  tests/tracking_validator.py
  tests/w3c_base.py
Labels: bug
