Repository Webperf-se/webperf_core, pull requests merged in 2024-11, with the labels that each got.

#688 Add `--credits` Option to Display Contributors and Dependencies
  .github/workflows/update-software.yml
  CREDITS.md
  README.md
  credits.md
  default.py
  helpers/credits_helper.py
  locales/en/LC_MESSAGES/webperf-core.mo
  locales/en/LC_MESSAGES/webperf-core.po
  locales/gov/LC_MESSAGES/webperf-core.mo
  locales/gov/LC_MESSAGES/webperf-core.po
  locales/sv/LC_MESSAGES/webperf-core.mo
  locales/sv/LC_MESSAGES/webperf-core.po
  software-full.json
  software-sources.json
  update_software.py
Labels: enhancement

#692 Remove Internet access requirement to run local Tests
  .github/workflows/update-software.yml
  defaults/mdn-rules.json
  helpers/credits_helper.py
  tests/css_validator_w3c.py
  tests/html_validator_w3c.py
  update_mdn_sources.py
Labels: enhancement

#702 Data object returned by Yellow Lab Tools Test was always empty
  tests/frontend_quality_yellow_lab_tools.py
Labels: bug

#710 Moved sites.json to defaults folder
  .github/workflows/regression-test-404.yml
  .github/workflows/regression-test-a11y-statement.yml
  .github/workflows/regression-test-css.yml
  .github/workflows/regression-test-docker-image.yml
  .github/workflows/regression-test-email.yml
  .github/workflows/regression-test-google-lighthouse-based.yml
  .github/workflows/regression-test-html.yml
  .github/workflows/regression-test-http.yml
  .github/workflows/regression-test-pa11y.yml
  .github/workflows/regression-test-sitespeed.yml
  .github/workflows/regression-test-software.yml
  .github/workflows/regression-test-standard-files.yml
  .github/workflows/regression-test-tracking.yml
  .github/workflows/regression-test-webbkoll.yml
  .github/workflows/regression-test-ylt.yml
  defaults/sites.json
  docker/run-with-mounted-folder.ps1
  docker/run.ps1
  docs/getting-started-docker.md
  docs/getting-started-github-actions.md
Labels: breaking-change

#707 Make Lighthouse/YLT/Pa11y work in GH Action Docker regression test
  .github/workflows/regression-test-docker-image.yml
  Dockerfile
  credits.md
  pa11y-docker-config.json
  pally-config.json
Labels: enhancement

#720 Fix Translation Regression Test error
  helpers/credits_helper.py
  locales/en/LC_MESSAGES/http_validator.mo
  locales/en/LC_MESSAGES/http_validator.po
  locales/gov/LC_MESSAGES/http_validator.mo
  locales/gov/LC_MESSAGES/http_validator.po
  locales/sv/LC_MESSAGES/http_validator.mo
  locales/sv/LC_MESSAGES/http_validator.po
Labels: bug

#730 Update default.py
  default.py
Labels: ignore-for-release

#732 Call to dependency check used old (removed) call in Docker Image Regression Test
  .github/workflows/regression-test-docker-image.yml
Labels: bug

#733 CSS Test is not using unique rules for style-attributes
  tests/css_validator_w3c.py
Labels: bug

#734 CSS Test is not handling relative url traversal correctly
  tests/css_validator_w3c.py
Labels: bug

#744 get_data_from_sitespeed method is not using 'failed' mark
  helpers/sitespeed_helper.py
Labels: bug
