Repository Webperf-se/webperf_core, pull requests merged in 2025-01, with the labels that each got.

#838 Yellow Lab Tools - Regression Test, revert Ubuntu version to 22.04
  .github/workflows/regression-test-ylt.yml
Labels: bug

#842 Lighthouse Based Tests - Output file should include same source as seen in review
  tests/lighthouse_base.py
Labels: breaking-change

#848 Update Carbon - Was unable to generate percentile
  default.py
  helpers/carbon_rating_helper.py
Labels: bug

#850 Carbon Update - Now support files including failed test
  helpers/carbon_rating_helper.py
Labels: bug

#860 Sitespeed Based Tests - Added support for mobile
  default.py
  defaults/settings.json
  docs/settings-json.md
  helpers/setting_helper.py
  tests/sitespeed_base.py
Labels: enhancement

#849 Lighthouse based Tests - use lighthouse plugin inside sitespeed
  .github/workflows/regression-test-google-lighthouse-based.yml
  Dockerfile
  defaults/lighthouse-flags-locale-sv.json
  defaults/settings.json
  docs/settings-json.md
  helpers/setting_helper.py
  package.json
  tests/a11y_lighthouse.py
  tests/best_practice_lighthouse.py
  tests/lighthouse_base.py
  tests/performance_lighthouse.py
  tests/seo_lighthouse.py
  tests/sitespeed_base.py
  unittests/webperf.se/test-01-lighthouse-lhr.json
  unittests/webperf.se/test-01.har
  unittests/webperf.se/test-04-lighthouse-lhr.json
  unittests/webperf.se/test-04.har
  unittests/webperf.se/test-05-lighthouse-lhr.json
  unittests/webperf.se/test-05.har
  unittests/webperf.se/test-10-lighthouse-lhr.json
  unittests/webperf.se/test-10.har
Labels: breaking-change

#868 Include ALL changes in Release Notes
  .github/release.yml
  .github/workflows/update-software.yml
Labels: ignore-for-release

#889 Added support for using custom cache folder
  .github/workflows/regression-test-404.yml
  .github/workflows/regression-test-a11y-statement.yml
  .github/workflows/regression-test-css.yml
  .github/workflows/regression-test-energy-efficiency.yml
  .github/workflows/regression-test-google-lighthouse-based.yml
  .github/workflows/regression-test-html.yml
  .github/workflows/regression-test-http.yml
  .github/workflows/regression-test-lint-css.yml
  .github/workflows/regression-test-software.yml
  .github/workflows/regression-test-tracking.yml
  defaults/settings.json
  docs/settings-json.md
  engines/sitespeed_result.py
  helpers/credits_helper.py
  helpers/mdn_helper.py
  helpers/setting_helper.py
  helpers/update_software_helper.py
  tests/sitespeed_base.py
  tests/utils.py
Labels: enhancement

#899 Bump sitespeed to 36.1.0 and related packages
  Dockerfile
  chrome-custom.cjs
  package.json
Labels: enhancement

#916 Removed unused --sustainable flag in Google Lighthouse Based unittests
  .github/workflows/regression-test-google-lighthouse-based.yml
Labels: bug

#915 Sitespeed Based Tests - Crashed if file was found instead of directory
  tests/sitespeed_base.py
Labels: bug
